
name: push-scanner 
on: [push]

env:
  STK: ${{secrets.PTBOT}}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    name: scanner
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
   
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
          python -m pip install --upgrade pip
          pip install slack-notifications

    - name: scan branch
      id: scan_branch
      run: python scan.py
      continue-on-error: true

    - name: scan cond
      if: steps.scan_branch.outcome != 'success'
      run: echo 'error detected in branch'

    - name: alternative 
      if: steps.scan_branch.outcome == 'success'
      run: echo running on branch ${GITHUB_REF##*/}

  merge:
    needs: build
    name: decoy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: checkout main    
      uses: actions/checkout@v3
      with:
        ref: main 
    
    - name: branch creator 
      uses: peterjgrainger/action-create-branch@v2.2.0
      with:
        branch: 'dev'
    
    - name: displayer
      run: echo "to oblivion"
